### ISSUE TITLE
Failing to Fetch HTTP Redirect Feeds

### ISSUE THREAD

**Issue by cogdog** [cogdog/feed2js#25]
I'm failing to get a fetched feed for WordPress sites. Testing with `magpie_debug.php` -- e.g. 

https://lab.cogdogblog.com/feed2js/magpie_debug.php?url=http%3A%2F%2Fcogdogblog.com%2Ffeed

I get

`Warning: MagpieRSS: Failed to fetch http://cogdogblog.com/feed (HTTP Response: HTTP/1.1 301 Moved Permanently ) in /home/cogdog/subdomains/lab/feed2js/magpie/rss_fetch.inc on line 238
Error: MagpieRSS: Failed to fetch http://cogdogblog.com/feed (HTTP Response: HTTP/1.1 301 Moved Permanently )`

**Comment by Vulch** [comment]
Probably caused by Snoopy. Lines 631 and 632 of Snoopy.class.inc add the port number to the end of the request Host header for anything other than port 80. Your example first redirects to https, so for the second attempt Snoopy sets "Host: cogdogblog.com:443", Wordpress objects to the ":443" bit and redirects, Snoopy puts the :443 back again, Wordpress objects and redirects again, repeat until $maxredirs exceeded and the error gets thrown.

Commenting out those two lines appears to fix things without breaking other fetches.

**Comment by cogdog** [comment]
Thanks, that does work, and like you say, it still works with non WordPress feeds. I will update the repo for this change.
